# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Location-GeoTool-Plugin-Locapoint
version:      0.01
version_from: lib/Location/GeoTool/Plugin/Locapoint.pm
installdirs:  site
requires:
    Location::GeoTool:             1.98
    Math::Round:                   0.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
